const OPEN_LIGHTBOX = 'OPEN_LIGHTBOX';
const CLOSE_LIGHTBOX = 'CLOSE_LIGHTBOX';
const SET_CURR_IMG_ARRAY ='SET_CURR_IMG_ARRAY';
const SET_CURR_IMG ='SET_CURR_IMG';

export default {
    OPEN_LIGHTBOX,
    CLOSE_LIGHTBOX,
    SET_CURR_IMG_ARRAY,
    SET_CURR_IMG
}
