const OPEN_LIGHTBOX = 'OPEN_LIGHTBOX';
const CLOSE_LIGHTBOX = 'CLOSE_LIGHTBOX';
const SET_CURR_IMG_ARRAY = 'SET_CURR_IMG_ARRAY';
const SET_CURR_IMG = 'SET_CURR_IMG';
const ALLOW_NEXT = 'ALLOW_NEXT';
const DENY_NEXT = 'DENY_NEXT';
const ALLOW_PREV = 'ALLOW_PREV';
const DENY_PREV = 'DENY_PREV';
const RESET_INDEX='RESET_INDEX';

export default {
    OPEN_LIGHTBOX,
    CLOSE_LIGHTBOX,
    SET_CURR_IMG_ARRAY,
    SET_CURR_IMG,
    ALLOW_NEXT,
    DENY_NEXT,
    ALLOW_PREV,
    DENY_PREV,
    RESET_INDEX
}
